/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as KolDirectoryIndexRouteImport } from './routes/kol-directory/index'
import { Route as KolDirectoryKolIdRouteImport } from './routes/kol-directory/$kolId'
import { Route as PipelineIndexRouteImport } from './routes/pipeline/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const KolDirectoryIndexRoute = KolDirectoryIndexRouteImport.update({
  id: '/kol-directory/',
  path: '/kol-directory/',
  getParentRoute: () => rootRouteImport,
} as any)
const KolDirectoryKolIdRoute = KolDirectoryKolIdRouteImport.update({
  id: '/kol-directory/$kolId',
  path: '/kol-directory/$kolId',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineIndexRoute = PipelineIndexRouteImport.update({
  id: '/pipeline/',
  path: '/pipeline/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/kol-directory/$kolId': typeof KolDirectoryKolIdRoute
  '/kol-directory/': typeof KolDirectoryIndexRoute
  '/pipeline/': typeof PipelineIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/kol-directory/$kolId': typeof KolDirectoryKolIdRoute
  '/kol-directory': typeof KolDirectoryIndexRoute
  '/pipeline': typeof PipelineIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/kol-directory/$kolId': typeof KolDirectoryKolIdRoute
  '/kol-directory/': typeof KolDirectoryIndexRoute
  '/pipeline/': typeof PipelineIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/kol-directory/$kolId'
    | '/kol-directory/'
    | '/pipeline/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/kol-directory/$kolId'
    | '/kol-directory'
    | '/pipeline'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/kol-directory/$kolId'
    | '/kol-directory/'
    | '/pipeline/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  KolDirectoryKolIdRoute: typeof KolDirectoryKolIdRoute
  KolDirectoryIndexRoute: typeof KolDirectoryIndexRoute
  PipelineIndexRoute: typeof PipelineIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kol-directory/': {
      id: '/kol-directory/'
      path: '/kol-directory'
      fullPath: '/kol-directory/'
      preLoaderRoute: typeof KolDirectoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kol-directory/$kolId': {
      id: '/kol-directory/$kolId'
      path: '/kol-directory/$kolId'
      fullPath: '/kol-directory/$kolId'
      preLoaderRoute: typeof KolDirectoryKolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline/': {
      id: '/pipeline/'
      path: '/pipeline'
      fullPath: '/pipeline/'
      preLoaderRoute: typeof PipelineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  KolDirectoryKolIdRoute: KolDirectoryKolIdRoute,
  KolDirectoryIndexRoute: KolDirectoryIndexRoute,
  PipelineIndexRoute: PipelineIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
